=== Politecnicojic2022-01/HechosHistoricosXML/HechosHistoricos.dtd
<!ELEMENT HechosHistoricos (HechoHistorico)+>
        <!ATTLIST  HechoHistorico descripcion CDATA #REQUIRED>
        <!ELEMENT HechoHistorico (Fecha, Epoca?, PersonajeDestacado*)?>
        <!ELEMENT Epoca EMPTY>
        <!ELEMENT PersonajeDestacado ANY>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT FechaNacimiento (#PCDATA)>
        <!ELEMENT Fecha (Dia, Mes, Año)>
        <!ELEMENT Dia (#PCDATA)>
        <!ELEMENT Mes (#PCDATA)>
        <!ELEMENT Año (#PCDATA)>

=== Politecnicojic2022-01/HechosHistoricosXML/HechosHistoricos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HechosHistoricos SYSTEM "HechosHistoricos.dtd">

<HechosHistoricos>
    <HechoHistorico descripcion="">
        <Fecha>
            <Dia>01</Dia>
            <Mes>01</Mes>
            <Año>2022</Año>
        </Fecha>
        <Epoca/>
        <PersonajeDestacado>
            Test persona <Nombre>Juan</Nombre> y fecha de nacimiento: <FechaNacimiento>01/01/2022</FechaNacimiento>
        </PersonajeDestacado>
    </HechoHistorico>
</HechosHistoricos>
